/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Components;

import Classes.Cliente;
import Classes.VeiculoI;
import java.awt.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.OverlayLayout;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beatr
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form Page
     */
    public MainPage() {
        initComponents();
        clientsArrayList.add(c1);         
         clientsArrayList.add(c2);
         clientsArrayList.add(c3);
    }
    private ArrayList <Cliente> clientsArrayList = new ArrayList<Cliente>();    
    private ArrayList <VeiculoI> vehicleArrayList = new ArrayList<VeiculoI>();

    
    Cliente c1 = new Cliente("Beatriz", "Helena", "1234", "4321", "Sept");   
    Cliente c2 = new Cliente("Gabriel", "Helena", "1234", "4321", "Sept");
    Cliente c3 = new Cliente("Nath", "Helena", "1234", "4321", "Sept");

    private String selected = "Select a Tab";
    
    private javax.swing.JTable ClienteList = new javax.swing.JTable();
    private javax.swing.JTable VehicleList = new javax.swing.JTable();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ClientNav = new javax.swing.JButton();
        VahicleNav = new javax.swing.JButton();
        RentNav = new javax.swing.JButton();
        SellNav = new javax.swing.JButton();
        Label = new javax.swing.JLabel();
        Forms = new javax.swing.JTabbedPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 86));

        ClientNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\beatr\\Documents\\NetBeansProjects\\AluguelDeCarros\\src\\main\\java\\icons\\person.png")); // NOI18N
        ClientNav.setPreferredSize(new java.awt.Dimension(72, 72));
        ClientNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNavActionPerformed(evt);
            }
        });

        VahicleNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\beatr\\Documents\\NetBeansProjects\\AluguelDeCarros\\src\\main\\java\\icons\\car.png")); // NOI18N
        VahicleNav.setPreferredSize(new java.awt.Dimension(72, 72));
        VahicleNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VahicleNavActionPerformed(evt);
            }
        });

        RentNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\beatr\\Documents\\NetBeansProjects\\AluguelDeCarros\\src\\main\\java\\icons\\deal.png")); // NOI18N
        RentNav.setPreferredSize(new java.awt.Dimension(72, 72));

        SellNav.setIcon(new javax.swing.ImageIcon("C:\\Users\\beatr\\Documents\\NetBeansProjects\\AluguelDeCarros\\src\\main\\java\\icons\\loan.png")); // NOI18N
        SellNav.setPreferredSize(new java.awt.Dimension(72, 72));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(ClientNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(VahicleNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(190, 190, 190)
                .addComponent(RentNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addComponent(SellNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VahicleNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RentNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SellNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        Label.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Forms)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Label, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Forms, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Label.setText(selected);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void updateClientList(){
            Object Columns[] = {"Nome","CPF"};
            Object Rows[][] = new Object[clientsArrayList.size()][2];
            for(int i = 0; i < clientsArrayList.size(); i++){
                Rows[i][0] = clientsArrayList.get(i).getNome();                
                Rows[i][1] = clientsArrayList.get(i).getCPF();
            }
            DefaultTableModel model = new DefaultTableModel(Rows, Columns);
            ClienteList.setModel(model);
            jScrollPane2.setViewportView(ClienteList);
    }
    public void updateVehicleList(){
            Object Columns[] = {"Placa","Ano", "Marca", "Tipo", "Estado"};
            Object Rows[][] = new Object[vehicleArrayList.size()][5];
            for(int i = 0; i < vehicleArrayList.size(); i++){
                Rows[i][0] = vehicleArrayList.get(i).getPlaca();                
                Rows[i][1] = vehicleArrayList.get(i).getAno();
                Rows[i][2] =  vehicleArrayList.get(i).getMarca();
                Rows[i][3] = vehicleArrayList.get(i).getClass().getSimpleName();
                Rows[i][4] = vehicleArrayList.get(i).getEstado();
            }
            DefaultTableModel model = new DefaultTableModel(Rows, Columns);
            VehicleList.setModel(model);
            jScrollPane2.setViewportView(VehicleList);
    }
    
    public void DeleteClient(){
        Integer i = ClienteList.getSelectedRow();
        if(i != -1){
            clientsArrayList.remove(clientsArrayList.get(i));
        }
        updateClientList();
    }
     public void DeleteVehicle(){
        Integer i = VehicleList.getSelectedRow();
        if(i != -1){
            vehicleArrayList.remove(vehicleArrayList.get(i));
        }
        updateClientList();
    }
    
    public void Delete(){
        switch(selected){
            default:
                return;
            case "Clients":
                DeleteClient();
            case "Vehicles":
                DeleteVehicle();
        }
    }
    private void ClientNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNavActionPerformed
            this.selected = "Clients";
            Label.setText(selected);
            updateClientList();
            ClienteForm cp = new ClienteForm();
            Forms.removeAll();
            Forms.add(cp);
           
            
    }//GEN-LAST:event_ClientNavActionPerformed

    private void VahicleNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VahicleNavActionPerformed
       this.selected = "Vehicles";
       Label.setText(selected);
       updateVehicleList();
       Forms.removeAll();
    }//GEN-LAST:event_VahicleNavActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Delete();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientNav;
    private javax.swing.JTabbedPane Forms;
    private javax.swing.JLabel Label;
    private javax.swing.JButton RentNav;
    private javax.swing.JButton SellNav;
    private javax.swing.JButton VahicleNav;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}

