/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Classes.Cliente;
import Classes.Locacao;
import Classes.VeiculoI;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author beatr
 */
public final class RentForm extends javax.swing.JPanel {
    
    public ArrayList<Cliente> FilteredclientsArrayList = new ArrayList<Cliente>();
    public ArrayList<VeiculoI> FilteredvehicleArrayList = new ArrayList<VeiculoI>();
     public javax.swing.JTable FilteredClienteList = new javax.swing.JTable();
    public javax.swing.JTable FilteredVehicleList = new javax.swing.JTable(); 
    private MainPage main;
    
    public RentForm(MainPage main) {
        initComponents();
        this.main = main;
        this.FilteredvehicleArrayList = filterVehicles();
        this.FilteredclientsArrayList = filterClients();
        updateTables();
    }
    
    public ArrayList<VeiculoI> filterVehicles(){
        Stream<VeiculoI> fv = main.vehicleArrayList.stream().filter(v -> v.getEstado().getAtual() == "Disponivel" || v.getEstado().getAtual() == "Novo" );
        ArrayList<VeiculoI> lv = new ArrayList(fv.collect(Collectors.toList()));
        return lv;
    }
    public ArrayList<Cliente> filterClients(){
        Stream<Cliente> fc = main.clientsArrayList.stream().filter(c-> !main.findClientRent(c));
        ArrayList<Cliente> lc = new ArrayList(fc.collect(Collectors.toList()));
        return lc;
    }
   
    public void updateTables(){
        this.FilteredvehicleArrayList = filterVehicles();
        this.FilteredclientsArrayList = filterClients();
        Object ColumnsCliente[] = {"Nome"};
        Object RowsCliente[][] = new Object[this.FilteredclientsArrayList.size()][1];
        for (int i = 0; i < this.FilteredclientsArrayList.size(); i++){
            RowsCliente[i][0] = this.FilteredclientsArrayList.get(i).getNome();
        }
        Object ColumnsVeiculo[] = {"Placa", "Valor Diário"};
        Object RowsVeiculo[][] = new Object[this.FilteredvehicleArrayList.size()][2];
        for(int i = 0; i< this.FilteredvehicleArrayList.size(); i++){
            RowsVeiculo[i][0] = this.FilteredvehicleArrayList.get(i).getPlaca();
            RowsVeiculo[i][1] = this.FilteredvehicleArrayList.get(i).getValorDiariaLocacao();
        }
        DefaultTableModel modelClientes = new DefaultTableModel(RowsCliente, ColumnsCliente);
        DefaultTableModel modelVeiculos = new DefaultTableModel(RowsVeiculo, ColumnsVeiculo);
        FilteredClienteList.setModel(modelClientes);
        FilteredVehicleList.setModel(modelVeiculos);
        jScrollPane1.setViewportView(FilteredClienteList);
        jScrollPane3.setViewportView(FilteredVehicleList);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Locar = new javax.swing.JButton();
        Devolver = new javax.swing.JButton();
        LDias = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LValor = new javax.swing.JLabel();
        Carregar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClienteTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        LCPF = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        VeiculoTable = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        LMarca = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        LAno = new javax.swing.JLabel();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("jButton1");

        jButton3.setText("jButton3");

        Locar.setText("Rent");
        Locar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocarActionPerformed(evt);
            }
        });

        Devolver.setText("Return");
        Devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DevolverActionPerformed(evt);
            }
        });

        LDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LDiasActionPerformed(evt);
            }
        });

        jLabel1.setText("Dias:");

        jLabel2.setText("Valor:");

        LValor.setText("N/A");

        Carregar.setText("Load");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });

        jLabel3.setText("Cliente:");

        ClienteTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(ClienteTable);

        jLabel4.setText("CPF:");

        LCPF.setText("N/A");

        jLabel7.setText("Veiculo:");

        VeiculoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(VeiculoTable);

        jLabel5.setText("Marca:");

        LMarca.setText("N/A");

        jLabel6.setText("Ano:");

        LAno.setText("N/A");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LDias, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LCPF))))
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(84, 84, 84))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addGap(78, 78, 78)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(89, 89, 89)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LAno)
                                    .addComponent(LMarca)
                                    .addComponent(LValor))))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(Locar, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LMarca)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(LCPF)))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LAno))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LDias, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(LValor))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carregar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Locar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(158, 158, 158))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void DevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DevolverActionPerformed
        int rentIndex = main.rentList.getSelectedRow();
        Locacao rent = main.rentArrayList.get(rentIndex);
        main.rentArrayList.remove(rent);
        VeiculoI v = rent.getVeiculo();
        v.devolver();
        main.updateRentList();
        updateTables();
    }//GEN-LAST:event_DevolverActionPerformed

    private void LocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocarActionPerformed
        int clienteindex = FilteredClienteList.getSelectedRow();
        int vehicleindex = FilteredVehicleList.getSelectedRow();
        if(vehicleindex > -1 && clienteindex > -1){
        Cliente c = FilteredclientsArrayList.get(clienteindex);
        VeiculoI v = FilteredvehicleArrayList.get(vehicleindex);
        Calendar hoje = Calendar.getInstance();
        int dias = Integer.parseInt(LDias.getText());
        double valor = v.getValorDiariaLocacao()*dias;
        main.createRent(c, v, hoje, dias, valor);
        main.updateRentList();
        updateTables();
        }
        
    }//GEN-LAST:event_LocarActionPerformed

    private void LDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LDiasActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed

        int rentindex = main.rentList.getSelectedRow();
        Locacao rent = main.rentArrayList.get(rentindex);
        Cliente c = rent.getCliente();
        VeiculoI v = rent.getVeiculo();
        LCPF.setText(c.getCPF());
        LAno.setText(String.valueOf(v.getAno()));
        LDias.setText(String.valueOf(rent.getDias()));
        LValor.setText(String.valueOf(rent.getValor()));
        LMarca.setText(v.getMarca().getAtual());
       
        updateTables();
    }//GEN-LAST:event_CarregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Carregar;
    private javax.swing.JTable ClienteTable;
    private javax.swing.JButton Devolver;
    private javax.swing.JLabel LAno;
    private javax.swing.JLabel LCPF;
    private javax.swing.JTextField LDias;
    private javax.swing.JLabel LMarca;
    private javax.swing.JLabel LValor;
    private javax.swing.JButton Locar;
    private javax.swing.JTable VeiculoTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
